version: '3'

services:
  app:
    container_name: farmvest-p4
    image: node:18-alpine
    volumes:
      - ./:/app
    working_dir: /app
    command: sh -c "yarn && yarn dev"
    ports:
      - '5173:5173'
